title: Zendesk Garden Jekyll Theme
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

baseurl: ds_template

search_enabled: true
auto_page_title: false

sidebar:
  - label: Site Editing How-tos
    children:
      - getting-started
      - sidebar
      - search
      - relative-nav
      - additional-config
      - development
  - label: Postgresql Development
    children:
      - sessiondata
      - retention_queries
  - label: Donor Data
      - donor_data