title: Zendesk Garden Jekyll Theme
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

baseurl: ds_template

search_enabled: true
auto_page_title: false

sidebar:
  - getting-started
  - label: Customization
    children:
      - sidebar
      - search
      - relative-nav
      - additional-config
  - label: Postgresql Development
    children:
      - sessiondata
      - testdoc2
  - development